RECIPES = {
    'Boxing Gloves': ('weapon', True, [('Crimson String', 1, 'material', False), ('Cue Tape', 1, 'material', False)]),
    'Wooden Spear': ('weapon', True, [('Spore Cap', 10, 'material', False)]),
    'Wooden Bow': ('weapon', True, [('Frog Leg', 10, 'material', False)]), 
    'Gnarled Wand': ('weapon', True, [('Bean Slices', 10, 'material', False)]), 
    'Farmer Brim': ('armor', True, [('Spore Cap', 4, 'material', False)]), 
    'Orange Tee': ('armor', True, [('Thread', 1, 'material', False)]), 
    'Torn Jeans': ('armor', True, [('Frog Leg', 6, 'material', False), ('Thread', 10, 'material', False)]),
    'Flip Flops': ('armor', True, [('Bean Slices', 12, 'material', False), ('Grass Leaf', 5, 'choppin', False)]),
    'Copper Pickaxe': ('tool', True, [('Copper Ore', 10, 'mining', False)]), 
    'Cramped Mining Pouch': ('bag', True, [('Copper Ore', 50, 'mining', False)]), 
    'Copper Chopper': ('tool', True, [('Oak Logs', 6, 'choppin', False), ('Thread', 5, 'material', False)]), 
    'Cramped Choppin Pouch': ('bag', True, [('Oak Logs', 50, 'choppin', False)]), 
    'Leather Cap': ('armor', True, [('Frog Leg', 30, 'material', False)]),
    'The Stingers': ('weapon', True, [('Copper Bar', 20, 'mining', False), ('Trusty Nails', 20, 'material', False)]),
    'Cramped Food Pouch': ('bag', True, [('Nomwich', 30, 'food', False), ('Hot Dog', 20, 'food', False), ('Copper Bar', 5, 'mining', False)]),
    'Cramped Material Pouch': ('bag', True, [('Trusty Nails', 80, 'material', False), ('Frog Leg', 50, 'material', False)]),
    'Copper Helmet': ('armor', True, [('Copper Bar', 20, 'mining', False), ('Bean Slices', 40, 'material', False)]),
    'Copper Platebody': ('armor', True, [('Copper Bar', 25, 'mining', False), ('Trusty Nails', 120, 'material', False)]),
    'Copper Platelegs': ('armor', True, [('Copper Bar', 30, 'mining', False), ('Bleach Logs', 150, 'choppin', False)]),
    'Copper Boots': ('armor', True, [('Copper Bar', 75, 'mining', False)]),
    'Militia Helm': ('armor', True, [('Iron Bar', 15, 'mining', False), ('Copper Ore', 80, 'mining', False), ('Copper Helmet', 1, 'armor', True)]),
    'Thief Hood': ('armor', True, [('Iron Bar', 15, 'mining', False), ('Thread', 40, 'material', False), ('Copper Helmet', 1, 'armor', True)]),
    'Top Hat': ('armor', True, [('Iron Bar', 15, 'mining', False), ('Oak Logs', 150, 'choppin', False), ('Copper Helmet', 1, 'armor', True)]),
    'Party Hat': ('armor', False, [('Iron Bar', 150, 'mining', False), ('Copper Helmet', 1, 'armor', True)]),
    'Steel Axe': ('weapon', True, [('Slime Sludge', 125, 'material', False), ('Boring Brick', 125, 'material', False)]),
    'Birch Longbow': ('weapon', True, [('Slime Sludge', 125, 'material', False), ('Bleach Logs', 250, 'choppin', False)]),
    'Quarterstaff': ('weapon', True, [('Slime Sludge', 125, 'material', False), ('Copper Bar', 100, 'mining', False)]),
    'Copper Band': ('armor', True, [('Copper Bar', 300, 'mining', False)]),
    'Iron Pickaxe': ('tool', True, [('Iron Bar', 10, 'mining', False), ('Carrot Cube', 150, 'material', False)]),
    'Small Mining Pouch': ('bag', True, [('Iron Ore', 500, 'mining', False)]),
    'Iron Hatchet': ('tool', True, [('Jungle Logs', 200, 'choppin', False), ('Boring Brick', 100, 'material', False)]),
    'Small Choppin Pouch': ('bag', True, [('Bleach Logs', 500, 'choppin', False)]),
    'Iron Helmet': ('armor', True, [('Iron Bar', 40, 'mining', False), ('Goblin Ear', 300, 'material', False)]),
    'Iron Platebody': ('armor', True, [('Iron Bar', 50, 'mining', False), ('Jungle Logs', 600, 'choppin', False)]),
    'Iron Platelegs': ('armor', True, [('Iron Bar', 70, 'mining', False), ('Boring Brick', 225, 'material', False)]),
    'Anvil Tab 2': ('misc', False, [('Iron Bar', 100, 'mining', False), ('Chain Link', 200, 'material', False), ('Jungle Logs', 400, 'choppin', False), ('Bullfrog Horn', 250, 'material', False)]),
    'Blue Tee': ('armor', True, [('Spore Cap', 25, 'material', False), ('Oak Logs', 50, 'choppin', False), ('Orange Tee', 1, 'armor', True)]),
    'Sleek Shank': ('armor', True, [('Thread', 300, 'material', False), ('Wooden Spear', 2, 'weapon', True), ('Wooden Bow', 1, 'weapon', True), ('Gnarled Wand', 1, 'weapon', True)]),
    'Iron Boots': ('armor', True, [('Trusty Nails', 500, 'material', False), ('Iron Bar', 125, 'mining', False), ('Copper Boots', 1, 'armor', True)]),
    'Steel Band': ('armor', True, [('Iron Bar', 600, 'mining', False)]),
    'Purple Tupacband': ('armor', True, [('Bleach Logs', 100, 'choppin', False), ('Iron Ore', 50, 'mining', False), ('Crude Oil', 60, 'mining', False)]),
    'Icing Ironbite': ('food', True, [('Iron Ore', 5, 'mining', False), ('Small Mana Potion', 2, 'food', False)]), 
    'Saucy Logfries': ('food', True, [('Jungle Logs', 6, 'choppin', False), ('Small Life Potion', 3, 'food', False)]), 
    'Goo Galoshes': ('armor', True, [('Slime Sludge', 100, 'material', False), ('Jungle Logs', 40, 'choppin', False), ('Copper Boots', 1, 'armor', True)]),
    'Fur Shirt': ('armor', True, [('Goblin Ear', 500, 'material', False), ('Iron Bar', 500, 'mining', False)]), 
    'Hide Shirt': ('armor', True, [('Bleach Logs', 325, 'choppin', False), ('Copper Platebody', 1, 'armor', True), ('Steel Axe', 1, 'weapon', True)]), 
    'Eco Friendly Oil': ('mining', True, [('Crude Oil', 1, 'mining', False), ('Grass Leaf', 1, 'choppin', False)]), 
    'Dooble Goopi': ('armor', True, [('Slime Sludge', 1000, 'material', False), ('Copper Band', 1, 'armor', True), ('Steel Band', 1, 'armor', True)]), 
    'Bleached Designer Wode Patch Pants': ('armor', True, [('Torn Jeans', 3, 'armor', True), ('Plank', 275, 'material', False), ('Bleach Logs', 700, 'choppin', False)]), 
    'Dirty Coal Miner Baggy Soot Pants': ('armor', True, [('Torn Jeans', 3, 'armor', True), ('Iron Ore', 200, 'mining', False)]), 
    'Peanut': ('food', True, [('Hot Dog', 2, 'food', False), ('Copper Ore', 1, 'mining', False), ('Bleach Logs', 1, 'choppin', False)]), 
    'Golden Peanut': ('food', False, [('Not Yet', 1, '', False), ('Copper Ore', 1, 'mining', False)]), 
    'Blunderbag': ('bag', True, [('Spore Tee', 2, 'armor', False), ('Green Headband', 1, 'helmet', False), ('Spore Cap', 150, 'material', False)]), 
    'Purple Tee': ('armor', True, [('Red Spore Cap', 40, 'material', False), ('Bleach Logs', 100, 'choppin', False), ('Orange Tee', 1, 'armor', True)]), 
    'Green Tee': ('armor', True, [('Thread', 150, 'material', False), ('Spore Tee', 1, 'armor', False), ('Orange Tee', 1, 'armor', True)]), 
    'Black Tee': ('armor', True, [('Orange Tee', 5, 'armor', True), ('Blue Tee', 2, 'armor', True), ('Purple Tee', 2, 'armor', True), ('Green Tee', 2, 'armor', True)]), 
    'Blunderhills NPC Completion Token': ('misc', False, [('Easy Blunderhills NPC Token', 1, 'misc', False), ('Med Blunderhills NPC Token', 1, 'misc', False), ('Hard Blunderhills NPC Token', 1, 'misc', False)]), 
    'Blunder Skills Completion Token': ('misc', False, [('Not Yet', 1, '', False), ('Not Yet', 2, '', False)]), 
    'Blunderhills Misc Completion Token': ('misc', False, [('Not Yet', 1, '', False), ('Not Yet', 1, '', False)]), 
    'Easy Blunderhills NPC Token': ('misc', False, [('Woodsman Token', 1, 'misc', False), ('Glumlee Token', 1, 'misc', False), ('Stiltzcho Token', 1, 'misc', False), ('Funguy Token', 1, 'misc', False)]), 
    'Med Blunderhills NPC Token': ('misc', False, [('Krunk Token', 1, 'misc', False), ('Tiki Chief Token', 1, 'misc', False), ('Dog Bone Token', 1, 'misc', False), ('Papua Piggea Token', 1, 'misc', False)]), 
    'Hard Blunderhills NPC Token': ('misc', False, [('Picnic Token', 69, 'misc', False), ('TP Pete Token', 1, 'misc', False), ('Sproutinald Token', 1, 'misc', False), ('Dazey Token', 1, 'misc', False)]), 
    'Amarok Helmet': ('armor', False, [('Amarok Slab', 20, 'misc', False), ('Forest Fibres', 2500, 'choppin', False), ('Woodular Circle', 5, 'material', False)]), 
    'Amarok Bodyplate': ('armor', False, [('Amarok Slab', 10, 'misc', False), ('Iron Bar', 300, 'mining', False), ('Corn Kernels', 600, 'material', False)]), 
    'Amarok Hinds': ('armor', False, [('Amarok Slab', 6, 'misc', False), ('Chain Link', 300, 'material', False), ('Bullfrog Horn', 500, 'material', False)]), 
    'Amarok Paws': ('armor', False, [('Amarok Slab', 5, 'misc', False), ('Grass Leaf', 125, 'choppin', False), ('Iron Boots', 1, 'armor', True)]), 
    'Chaotic Amarok Pendant': ('armor', False, [('Chaotic Amarok Slab', 4, 'misc', False), ('Amarok Slab', 10, 'misc', False), ('Distilled Water', 25, 'material', False)]), 
    'Copper Fish Rod': ('tool', True, [('Copper Bar', 200, 'mining', False), ('Goldfish', 180, 'fish', False)]), 
    'Cramped Fish Pouch': ('bag', True, [('Goldfish', 180, 'fish', False)]), 
    'Copper Netted Net': ('tool', True, [('Jungle Logs', 500, 'choppin', False), ('Fly', 400, 'bug', False)]), 
    'Cramped Bug Pouch': ('bag', True, [('Fly', 180, 'bug', False)]),
    'Iron Fishing Rod': ('tool', True, [('Iron Bar', 300, 'mining', False), ('Hermit Can', 650, 'fish', False), ('Distilled Water', 3, 'material', False)]), 
    'Small Fish Pouch': ('bag', True, [('Hermit Can', 425, 'fish', False), ('Distilled Water', 2, 'material', False)]), 
    'Reinforced Net': ('tool', True, [('Forest Fibres', 800, 'choppin', False), ('Butterfly', 850, 'bug', False), ('Distilled Water', 3, 'material', False)]), 
    'Small Bug Pouch': ('bag', True, [('Butterfly', 425, 'bug', False), ('Distilled Water', 2, 'material', False)]), 
    'Gold Helmet': ('armor', True, [('Fly', 2000, 'bug', False), ('Copper Helmet', 1, 'armor', True), ('Gold Bar', 200, 'mining', False)]), 
    'Gold Platebody': ('armor', True, [('Pocket Sand', 1500, 'material', False), ('Copper Platebody', 1, 'armor', True), ('Gold Bar', 250, 'mining', False)]), 
    'Gold Platelegs': ('armor', True, [('Goldfish', 500, 'fish', False), ('Copper Platelegs', 1, 'armor', True), ('Gold Bar', 300, 'mining', False)]), 
    'Gold Boots': ('armor', True, [('Gold Bar', 600, 'mining', False), ('Iron Boots', 1, 'armor', True), ('Distilled Water', 4, 'material', False)]), 
    'Bandage Wraps': ('weapon', True, [('Cue Tape', 5000, 'material', False), ('The Stingers', 3, 'weapon', True), ('Potty Rolls', 2000, 'choppin', False)]), 
    'Royal Bayonet': ('weapon', True, [('Forest Fibres', 1250, 'choppin', False), ('Steel Axe', 1, 'weapon', True), ('Distilled Water', 8, 'material', False)]), 
    'Spiked Menace': ('weapon', True, [('Gold Bar', 250, 'mining', False), ('Birch Longbow', 1, 'weapon', True), ('Distilled Water', 8, 'material', False)]),
    'Starlight': ('weapon', True, [('Chain Link', 1000, 'material', False), ('Quarterstaff', 1, 'weapon', True), ('Distilled Water', 8, 'material', False)]), 
    'Gold Pickaxe': ('tool', False, [('Megalodon Tooth', 2500, 'material', False), ('Gold Bar', 400, 'mining', False), ('Iron Pickaxe', 1, 'tool', True)]), 
    'Average Mining Pouch': ('bag', True, [('Gold Ore', 2000, 'mining', False)]), 
    'Golden Axe': ('tool', False, [('Golden Dubloon', 5, 'misc', False), ('Crabby Cakey', 2000, 'material', False), ('Iron Hatchet', 1, 'tool', True)]), 
    'Average Choppin Pouch': ('bag', True, [('Forest Fibres', 2000, 'choppin', False)]), 
    'Gold Fishing Rod': ('tool', True, [('Hermit Can', 2500, 'fish', False), ('Leather Hide', 1000, 'material', False), ('Iron Fishing Rod', 1, 'tool', True)]), 
    'Average Fish Pouch': ('bag', True, [('Hermit Can', 2000, 'fish', False)]), 
    'Gilded Net': ('tool', True, [('Golden Dubloon', 5, 'misc', False), ('Butterfly', 2500, 'bug', False), ('Reinforced Net', 1, 'tool', True)]), 
    'Average Bug Pouch': ('bag', True, [('Butterfly', 2000, 'bug', False)]), 
    'Defenders Dignity': ('armor', True, [('Goldfish', 10000, 'fish', False), ('Golden Plop', 4, 'material', False), ('Distilled Water', 15, 'material', False)]), 
    'Strung Bludgeon': ('armor', True, [('Sleek Shank', 1, 'armor', True), ('Glass Shard', 4, 'material', False), ('Distilled Water', 20, 'material', False)]), 
    'Average Food Pouch': ('bag', True, [('Meat Pie', 400, 'food', False), ('Icing Ironbite', 700, 'food', True), ('Saucy Logfries', 700, 'food', True)]), 
    'Average Material Pouch': ('bag', True, [('Glass Shard', 1, 'material', False), ('Chain Link', 1700, 'material', False)]), 
    'Platinum Helmet': ('armor', True, [('Jellyfish', 2250, 'fish', False), ('Iron Helmet', 1, 'armor', True), ('Platinum Bar', 750, 'mining', False)]), 
    'Platinum Platbody': ('armor', True, [('Potato Remains', 5000, 'material', False), ('Iron Platebody', 1, 'armor', True), ('Platinum Bar', 1000, 'mining', False)]), 
    'Platinum Shins': ('armor', True, [('Sentient Cereal', 5000, 'bug', False), ('Iron Platelegs', 1, 'armor', True), ('Platinum Bar', 1250, 'mining', False)]), 
    'Platinum Boots': ('armor', True, [('Gold Boots', 1, 'armor', True), ('Tropilogs', 7000, 'choppin', False), ('Jellyfish', 3000, 'fish', False)]),
    'Bullet': ('food', True, [('Forest Fibers', 10, 'choppin', False), ('Fly', 10, 'bug', False)]),
    'Enforced Slasher': ('weapon', True, [('Nuget Cake', 3, 'material', False), ('Leather Hide', 2500, 'material', False), ('Royal Bayonet', 1, 'weapon', True)]),
    'Pharoah Bow': ('weapon', True, [('Woodular Circle', 3, 'material', False), ('Bloach', 1400, 'fish', False), ('Spiked Menace', 1, 'weapon', True)]),
    'Crows Nest': ('weapon', True, [('Golden Plop', 3, 'material', False), ('Fruitfly', 4000, 'bug', False), ('Starlight', 1, 'weapon', True)]),
    'Platinum Pickaxe': ('tool', True, [('Platinum Bar', 800, 'mining', False), ('Pincer Arm', 10500, 'material', False), ('Gold Pickaxe', 1, 'tool', True)]),
    'Sizable Mining Pouch': ('bag', True, [('Platinum Ore', 7500, 'mining', False)]),
    'Plat Hatchet': ('tool', True, [('Tropilogs', 7500, 'choppin', False)]),
    'Sizable Choppin Pouch': ('bag', True, [('Tropilogs', 7500, 'choppin', False)]),
    'Plat Fishing Rod': ('tool', True, [('Bloach', 2000, 'fish', False), ('Platinum Bar', 800, 'mining', False), ('Gold Fishing Rod', 1, 'tool', True)]), 
    'Sizable Fish Pouch': ('bag', True, [('Bloach', 2500, 'fish', False), ('Goldfish', 5000, 'fish', False)]),
    'Platinet': ('tool', True, [('Fruitfly', 7000, 'bug', False), ('Platinum Ore', 3000, 'mining', False), ('Gilded Net', 1, 'tool', True)]),
    'Sizable Bug Pouch': ('bag', True, [('Fruitfly', 7500, 'bug', False)]),
    'Sizable Food Pouch': ('bag', True, [('Golden Meat Pie', 9, 'food', False), ('Nuget Cake', 4, 'material', False)]),
    'Sizable Materials Pouch': ('bag', True, [('Golden Plop', 3, 'material', False), ('Woodular Circle', 4, 'material', False)]),
    'Anvil Tab 3': ('misc', False, [('Platinum Bar', 2000, 'mining', False), ('Bloach', 2000, 'fish', False), ('Fruitfly', 2000, 'bug', False), ('High Steaks', 1500, 'material', False)]),
    'Empty Box': ('misc', False, [('Hermit Can', 250, 'fish', False), ('Megalodon Tooth', 400, 'material', False), ('Distilled Water', 4, 'material', False)]),
    'FMJ Bullet': ('food', True, [('Gold Ore', 15, 'mining', False), ('Bullet', 2, 'food', True)]),
    'Viking Cap': ('armor', True, [('Militia Helm', 1, 'armor', True), ('Gold Bar', 400, 'mining', False), ('Glass Shard', 2, 'material', False)]),
    'Sleek Coif': ('armor', True, [('Thief Hood', 1, 'armor', True), ('Tropilogs', 2000, 'choppin', False), ('Glass Shard', 2, 'material', False)]),
    'Witch Hat': ('armor', True, [('Top Hat', 1, 'armor', True), ('Corn Kernels', 4000, 'material', False), ('Glass Shard', 2, 'material', False)]),
    'Studded Hide': ('armor', True, [('Hide Shirt', 1, 'armor', True), ('Megalodon Tooth', 4000, 'material', False), ('Nuget Cake', 1, 'material', False)]),
    'Feral Leathering': ('armor', True, [('Fur Shirt', 1, 'armor', True), ('Stick', 3000, 'material', False), ('Nuget Cake', 1, 'material', False)]),
    'Furled Robes': ('armor', True, [('Tattered Cloth', 1, 'armor', False), ('Leather Hide', 1500, 'material', False), ('Nuget Cake', 1, 'material', False)]), 
    'Cavern Trekkers': ('armor', True, [('Gold Boots', 1, 'armor', True), ('Distilled Water', 9, 'material', False), ('Copper Ore', 1500, 'mining', False), ('Iron Ore', 1200, 'mining', False)]),
    'Angler Boots': ('armor', True, [('Gold Boots', 1, 'armor', True), ('Distilled Water', 9, 'material', False), ('Goldfish', 1250, 'fish', False), ('Hermit Can', 1000, 'fish', False)]),
    'Logger Heels': ('armor', True, [('Gold Boots', 1, 'armor', True), ('Distilled Water', 9, 'material', False), ('Jungle Logs', 1600, 'choppin', False), ('Forest Fibres', 1000, 'choppin', False)]),
    'Bandito Boots': ('armor', True, [('Gold Boots', 1, 'armor', True), ('Distilled Water', 9, 'material', False), ('Fly', 2000, 'bug', False), ('Butterfly', 1250, 'bug', False)]),
    'Slurpin Herm': ('food', True, [('Hermit Can', 5, 'fish', False), ('Average Strength Potion', 2, 'food', False)]),
    'Buttered Toasted Butter': ('food', True, [('Butterfly', 5, 'bug', False), ('Kebab Sticks', 1, 'food', False)]),
    'Sandy Satchel': ('bag', True, [('Golden Plop', 1, 'material', False), ('Snakeskinventory Bag', 1, 'bag', False), ('Pocket Sand', 777, 'material', False)])}
